# Midterm Problem 5 - for loop comparing values in a range to the value 7
# Asmita Malakar


for i in range(10, 50, 4):
# 10 is the starting point for this for loop
# 50 signifies that the end point is 49 (one less than 49)
# 4 is the difference in the values for i [For ex: 10, 14, 18]
    print(i*i)

# The square of all values of i generated by the range function gets printed:
# [100,196,324, 484,676,900,1156,1444,1764,2116]